"""Read-only LangChain tools over the claims database.

Docstrings of the @tool functions are prompts: the investigator agent reads them to decide which tool to call,
so they say precisely what each tool returns, when to use it and when not to.

Safety, in layers:
- Every query is built with SQLAlchemy Core (``select(...).where(Column == value)``), which always sends
  values as bound parameters. There is no SQL string in this file and no text-to-SQL: the model chooses a tool
  and fills typed arguments; it never writes SQL. ``tests/test_sql_safety.py`` enforces this.
- Connections come from ``ReadOnlyDatabase``: a SELECT-only role, read-only transactions, and a privilege check.
- Identifiers are checked against their known formats before any query, so a malformed or injected value gets
  a clear error back instead of a database round trip.

Each tool uses ``response_format="content_and_artifact"`` like the policy tools: the LLM receives the result
as JSON text, and the graph receives the Pydantic result as the artifact for the tool call log.
"""

import re
import uuid
from collections.abc import Callable, Sequence
from datetime import UTC, date, datetime, timedelta

from langchain_core.tools import BaseTool, ToolException, tool
from pydantic import ValidationError
from sqlalchemy import and_, or_, select
from sqlalchemy.ext.asyncio import AsyncConnection

from app.db.models import Claim, Customer, Policy, PremiumPayment
from app.db.readonly import ReadOnlyDatabase
from app.tools.records import (
    OTHER_CUSTOMER_WINDOW_DAYS,
    SAME_CUSTOMER_WINDOW_DAYS,
    ClaimHistoryResult,
    CustomerProfileResult,
    PaymentHistoryResult,
    PolicyStatusResult,
    Row,
    SimilarClaimsResult,
    amount_band,
    build_claim_history,
    build_customer_profile,
    build_payment_history,
    build_policy_status,
    build_similar_claims,
)

# Formats generated by the seed and by the API: product prefix or CLM, 4-digit year, 6-digit sequence.
POLICY_NUMBER_PATTERN = re.compile(r"^(MOT|HLT|HOM)-\d{4}-\d{6}$")
CLAIM_NUMBER_PATTERN = re.compile(r"^CLM-\d{4}-\d{6}$")
# Safety cap on history rows; real customers have a handful. Counts are computed from what is fetched.
MAX_HISTORY_ROWS = 500
MAX_SIMILAR_ROWS = 50


def utc_today() -> date:
    """Today's date in UTC, the same convention ``build_rule_context`` uses for the submission date.

    Returns:
        The current UTC date.
    """
    return datetime.now(UTC).date()


def _checked(value: str, pattern: re.Pattern[str], kind: str, example: str) -> str:
    """Normalise an identifier from the model and reject anything that doesn't look like one.

    Args:
        value: Identifier as the model wrote it.
        pattern: The identifier's format.
        kind: "policy number" or "claim number", for the error message.
        example: A valid example, for the error message.

    Returns:
        The identifier, trimmed and upper-cased.

    Raises:
        ToolException: Returned to the model as the tool's output, so it can correct itself.
    """
    normalised = value.strip().upper()
    if not pattern.fullmatch(normalised):
        raise ToolException(
            f"{value!r} is not a valid {kind}; they look like {example}. "
            f"Use the {kind} exactly as it appears in the claim. Do not invent one."
        )
    return normalised


def _policy_number(value: str) -> str:
    return _checked(value, POLICY_NUMBER_PATTERN, "policy number", "MOT-2025-000123")


def _claim_number(value: str) -> str:
    return _checked(value, CLAIM_NUMBER_PATTERN, "claim number", "CLM-2026-000123")


def _not_found(kind: str, identifier: str) -> ToolException:
    return ToolException(f"No {kind} {identifier} exists. Re-check it against the claim; do not try guessed values.")


# ---- queries (Core only; every value is a bound parameter) --------------------------------------------------


async def fetch_policy(connection: AsyncConnection, policy_number: str) -> Row | None:
    """Load one policy's record.

    Args:
        connection: Read-only connection.
        policy_number: Exact policy number.

    Returns:
        The row, or None if no such policy exists.
    """
    statement = select(
        Policy.policy_number,
        Policy.product_type,
        Policy.status,
        Policy.start_date,
        Policy.end_date,
        Policy.lapsed_on,
        Policy.sum_insured,
        Policy.deductible,
        Policy.policy_document,
    ).where(Policy.policy_number == policy_number)
    return (await connection.execute(statement)).mappings().one_or_none()


async def fetch_payments(connection: AsyncConnection, policy_number: str) -> Sequence[Row]:
    """Load a policy's premium installments in order.

    Args:
        connection: Read-only connection.
        policy_number: Exact policy number.

    Returns:
        Installment rows, possibly empty.
    """
    statement = (
        select(
            PremiumPayment.installment_number,
            PremiumPayment.due_date,
            PremiumPayment.paid_date,
            PremiumPayment.amount,
            PremiumPayment.status,
        )
        .join(Policy, Policy.id == PremiumPayment.policy_id)
        .where(Policy.policy_number == policy_number)
        .order_by(PremiumPayment.installment_number)
    )
    return (await connection.execute(statement)).mappings().all()


async def fetch_customer_for_policy(connection: AsyncConnection, policy_number: str) -> Row | None:
    """Load the policyholder of a policy. Only non-identifying columns are selected.

    Args:
        connection: Read-only connection.
        policy_number: Exact policy number.

    Returns:
        Row with ``customer_id``, ``customer_ref``, ``kyc_status``, ``date_of_birth``; None if no such policy.
    """
    statement = (
        select(Customer.id.label("customer_id"), Customer.customer_ref, Customer.kyc_status, Customer.date_of_birth)
        .join(Policy, Policy.customer_id == Customer.id)
        .where(Policy.policy_number == policy_number)
    )
    return (await connection.execute(statement)).mappings().one_or_none()


async def fetch_customer_policies(connection: AsyncConnection, customer_id: uuid.UUID) -> Sequence[Row]:
    """Load every policy a customer holds.

    Args:
        connection: Read-only connection.
        customer_id: The customer's primary key.

    Returns:
        Policy rows ordered by start date.
    """
    statement = (
        select(Policy.policy_number, Policy.product_type, Policy.status, Policy.start_date, Policy.end_date)
        .where(Policy.customer_id == customer_id)
        .order_by(Policy.start_date)
    )
    return (await connection.execute(statement)).mappings().all()


async def fetch_customer_claims(
    connection: AsyncConnection, customer_id: uuid.UUID, exclude_claim_number: str | None
) -> Sequence[Row]:
    """Load a customer's claims on all of their policies, newest first.

    Args:
        connection: Read-only connection.
        customer_id: The customer's primary key.
        exclude_claim_number: A claim to leave out (the one under investigation), or None.

    Returns:
        Claim rows, capped at ``MAX_HISTORY_ROWS``.
    """
    statement = (
        select(
            Claim.claim_number,
            Policy.policy_number,
            Policy.product_type,
            Claim.incident_type,
            Claim.incident_date,
            Claim.claimed_amount,
            Claim.status,
            Claim.final_outcome,
        )
        .join(Policy, Policy.id == Claim.policy_id)
        .where(Policy.customer_id == customer_id)
        .order_by(Claim.incident_date.desc(), Claim.claim_number.desc())
        .limit(MAX_HISTORY_ROWS)
    )
    if exclude_claim_number is not None:
        statement = statement.where(Claim.claim_number != exclude_claim_number)
    return (await connection.execute(statement)).mappings().all()


async def fetch_claim_target(connection: AsyncConnection, claim_number: str) -> Row | None:
    """Load the facts about one claim that similarity is judged on.

    Args:
        connection: Read-only connection.
        claim_number: Exact claim number.

    Returns:
        The row, or None if no such claim exists.
    """
    statement = (
        select(
            Claim.id.label("claim_id"),
            Claim.claim_number,
            Claim.policy_id,
            Policy.customer_id,
            Claim.incident_type,
            Claim.incident_date,
            Claim.claimed_amount,
        )
        .join(Policy, Policy.id == Claim.policy_id)
        .where(Claim.claim_number == claim_number)
    )
    return (await connection.execute(statement)).mappings().one_or_none()


async def fetch_similar_candidates(connection: AsyncConnection, target: Row) -> Sequence[Row]:
    """Prefilter claims that might resemble the target; ``build_similar_claims`` makes the exact decision.

    Args:
        connection: Read-only connection.
        target: Row from ``fetch_claim_target``.

    Returns:
        Candidate rows: the same customer's claims within the same-customer window, and other customers'
        claims of the same type inside the date and amount bands.
    """
    incident = target["incident_date"]
    low, high = amount_band(target["claimed_amount"])
    same_customer = and_(
        Policy.customer_id == target["customer_id"],
        Claim.incident_date.between(
            incident - timedelta(days=SAME_CUSTOMER_WINDOW_DAYS), incident + timedelta(days=SAME_CUSTOMER_WINDOW_DAYS)
        ),
    )
    other_customer = and_(
        Policy.customer_id != target["customer_id"],
        Claim.incident_type == target["incident_type"],
        Claim.incident_date.between(
            incident - timedelta(days=OTHER_CUSTOMER_WINDOW_DAYS), incident + timedelta(days=OTHER_CUSTOMER_WINDOW_DAYS)
        ),
        Claim.claimed_amount.between(low, high),
    )
    statement = (
        select(
            Claim.claim_number,
            Claim.policy_id,
            Policy.policy_number,
            Policy.customer_id,
            Claim.incident_type,
            Claim.incident_date,
            Claim.claimed_amount,
            Claim.status,
        )
        .join(Policy, Policy.id == Claim.policy_id)
        .where(Claim.id != target["claim_id"], or_(same_customer, other_customer))
        .order_by(Claim.incident_date.desc())
        .limit(MAX_SIMILAR_ROWS)
    )
    return (await connection.execute(statement)).mappings().all()


# ---- tools ----------------------------------------------------------------------------------------------------


def _validation_message(error: ValidationError) -> str:
    """Tell the model which argument was wrong, so it can retry with a fix instead of failing the run."""
    return f"Invalid tool arguments: {error}. Correct them and call the tool again."


def build_sql_tools(database: ReadOnlyDatabase, clock: Callable[[], date] = utc_today) -> list[BaseTool]:
    """Create the read-only SQL tools bound to a database.

    A factory, like ``build_policy_tools``, so the graph injects the connection pool created once at startup
    and tests inject a stub or a test database.

    Args:
        database: Read-only database access.
        clock: Returns today's date; used only for defaults (age, claim-history reference date). Injected so
            tests are reproducible.

    Returns:
        [get_policy_status, get_claim_history, get_customer_profile, check_similar_claims, get_payment_history]
    """

    @tool(response_format="content_and_artifact", parse_docstring=True)
    async def get_policy_status(policy_number: str, on_date: date | None = None) -> tuple[str, PolicyStatusResult]:
        """Look up a policy's record: status, cover dates, lapse date, sum insured, deductible and wording document.

        Returns JSON. When on_date is given it also returns in_force_on_date (true, false, or null when the data
        cannot decide) and days_since_start, both computed exactly by code: use these values instead of working
        out dates yourself. Use this for nearly every claim, early, to confirm the policy exists, whether cover
        was in force on the incident date, and the sum insured. The policy_document value is the file to cite
        for wording. Do NOT use it for premium payment details (get_payment_history), the customer's KYC or
        other policies (get_customer_profile), or what the wording covers (get_coverage_section).

        Args:
            policy_number: Exactly as it appears in the claim, e.g. "MOT-2025-000123".
            on_date: The claim's incident date, YYYY-MM-DD. Omit only if the claim has no incident date.
        """
        number = _policy_number(policy_number)
        async with database.connect() as connection:
            row = await fetch_policy(connection, number)
        if row is None:
            raise _not_found("policy", number)
        result = build_policy_status(row, on_date)
        return result.model_dump_json(), result

    @tool(response_format="content_and_artifact", parse_docstring=True)
    async def get_claim_history(
        policy_number: str, exclude_claim_number: str | None = None, reference_date: date | None = None
    ) -> tuple[str, ClaimHistoryResult]:
        """List every claim the policyholder has made on ANY of their policies, newest first, with counts.

        Each claim has its incident type, date, amount, status and final outcome. The counts include
        other_claims_in_prior_12_months (incidents in the 365 days up to reference_date), rejected_claims and
        total_claimed_amount, computed exactly by code. Use this when claim frequency could matter: the policy is
        new, the amount is high, the loss type is often repeated, or the circumstances suggest a pattern. Always
        pass exclude_claim_number so the claim under investigation is not counted as its own history. Do NOT use
        it to look for a duplicate of this specific claim; check_similar_claims does that precisely. For a
        routine low-value claim on a long-standing policy it is usually unnecessary.

        Args:
            policy_number: Any policy of the customer, normally the one in the claim, e.g. "HOM-2025-000042".
            exclude_claim_number: The claim under investigation, e.g. "CLM-2026-000123".
            reference_date: The claim's incident date, YYYY-MM-DD; defaults to today.
        """
        number = _policy_number(policy_number)
        excluded = _claim_number(exclude_claim_number) if exclude_claim_number else None
        async with database.connect() as connection:
            customer = await fetch_customer_for_policy(connection, number)
            if customer is None:
                raise _not_found("policy", number)
            rows = await fetch_customer_claims(connection, customer["customer_id"], excluded)
        result = build_claim_history(customer["customer_ref"], rows, reference_date or clock(), excluded)
        return result.model_dump_json(), result

    @tool(response_format="content_and_artifact", parse_docstring=True)
    async def get_customer_profile(policy_number: str) -> tuple[str, CustomerProfileResult]:
        """Get facts about the policyholder: KYC status, age, customer-since date, and all their policies.

        Also returns the customer reference.
        KYC status is "verified", "pending" or "rejected". Names, contact details and addresses are deliberately
        not available; do not try to obtain them. Use this when identity or tenure could affect the decision:
        the amount is large, the policy is new, or the customer holds several policies whose status matters.
        The rules engine checks KYC on every claim by itself, so you do not need this tool only to confirm KYC
        on a routine claim. Do NOT use it for past claims (get_claim_history).

        Args:
            policy_number: Any policy of the customer, normally the one in the claim, e.g. "HLT-2025-000077".
        """
        number = _policy_number(policy_number)
        async with database.connect() as connection:
            customer = await fetch_customer_for_policy(connection, number)
            if customer is None:
                raise _not_found("policy", number)
            policies = await fetch_customer_policies(connection, customer["customer_id"])
        result = build_customer_profile(customer, policies, clock())
        return result.model_dump_json(), result

    @tool(response_format="content_and_artifact", parse_docstring=True)
    async def check_similar_claims(claim_number: str) -> tuple[str, SimilarClaimsResult]:
        """Find claims that resemble one specific claim, and say why each one matched.

        Match reasons: "exact_duplicate" (same policy, incident date and amount), "same_customer_near_date"
        (the same customer's claims within 30 days of the incident), and "other_customer_same_pattern" (other
        customers' claims of the same incident type within 3 days and 5% of the amount, a pattern seen in
        organised fraud). Each match includes days_apart and amount_difference_pct. An empty matches list means
        nothing similar exists. Use this when the claim could be a resubmission, when claim history shows
        claims close together, or when the circumstances look staged. Do NOT use it for a customer's general
        claim history (get_claim_history).

        Args:
            claim_number: The claim under investigation, e.g. "CLM-2026-000123".
        """
        number = _claim_number(claim_number)
        async with database.connect() as connection:
            target = await fetch_claim_target(connection, number)
            if target is None:
                raise _not_found("claim", number)
            candidates = await fetch_similar_candidates(connection, target)
        result = build_similar_claims(target, candidates)
        return result.model_dump_json(), result

    @tool(response_format="content_and_artifact", parse_docstring=True)
    async def get_payment_history(policy_number: str, on_date: date | None = None) -> tuple[str, PaymentHistoryResult]:
        """List a policy's premium installments (due, paid, amount, status, days late) with on-time/late/missed counts.

        With on_date, missed_on_or_before_date counts installments missed with a due date on or before it.
        Use this when the policy is lapsed or cancelled, when get_policy_status shows a lapse date near the
        incident date, or when you need to show whether premiums were paid up when the incident happened.
        Do NOT use it for an active policy with no lapse date unless payment behaviour is relevant to the claim;
        for routine claims it adds nothing.

        Args:
            policy_number: Exactly as it appears in the claim, e.g. "HLT-2025-000077".
            on_date: The claim's incident date, YYYY-MM-DD. Optional.
        """
        number = _policy_number(policy_number)
        async with database.connect() as connection:
            policy = await fetch_policy(connection, number)
            if policy is None:
                raise _not_found("policy", number)
            payments = await fetch_payments(connection, number)
        result = build_payment_history(policy, payments, on_date)
        return result.model_dump_json(), result

    tools: list[BaseTool] = [
        get_policy_status,
        get_claim_history,
        get_customer_profile,
        check_similar_claims,
        get_payment_history,
    ]
    for sql_tool in tools:
        # A ToolException (bad identifier, record not found) becomes the tool's output, so the ReAct loop can
        # correct itself. Anything else (database down, ReadOnlyViolationError) still raises: infrastructure
        # and security failures must stop the run, not be narrated around by the model.
        sql_tool.handle_tool_error = True
        sql_tool.handle_validation_error = _validation_message
    return tools
