"""Initial schema: customers, policies, premium_payments, claims, claim_runs, audit_log.

Autogenerated from app/db/models.py, then reviewed by hand. The only manual addition is the append-only
trigger on audit_log at the end of upgrade(), which autogenerate cannot detect.

Revision ID: 0001
Revises:
Create Date: 2026-09-15 10:34:44.824051
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = '0001'
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('customers',
    sa.Column('customer_ref', sa.String(length=16), nullable=False),
    sa.Column('full_name', sa.String(length=120), nullable=False),
    sa.Column('email', sa.String(length=254), nullable=False),
    sa.Column('phone', sa.String(length=20), nullable=False),
    sa.Column('date_of_birth', sa.Date(), nullable=False),
    sa.Column('city', sa.String(length=80), nullable=False),
    sa.Column('kyc_status', sa.Enum('verified', 'pending', 'rejected', name='kyc_status', native_enum=False, create_constraint=True, length=32), nullable=False),
    sa.Column('id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_customers')),
    sa.UniqueConstraint('customer_ref', name=op.f('uq_customers_customer_ref')),
    sa.UniqueConstraint('email', name=op.f('uq_customers_email'))
    )
    op.create_table('policies',
    sa.Column('policy_number', sa.String(length=24), nullable=False),
    sa.Column('customer_id', sa.Uuid(), nullable=False),
    sa.Column('product_type', sa.Enum('motor', 'health', 'home', name='product_type', native_enum=False, create_constraint=True, length=32), nullable=False),
    sa.Column('status', sa.Enum('active', 'lapsed', 'expired', 'cancelled', name='status', native_enum=False, create_constraint=True, length=32), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('end_date', sa.Date(), nullable=False, comment='Last day of cover, inclusive'),
    sa.Column('lapsed_on', sa.Date(), nullable=True, comment='First day without cover after a missed premium'),
    sa.Column('sum_insured', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('deductible', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('annual_premium', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('policy_document', sa.String(length=120), nullable=False, comment='Wording PDF that citations refer to'),
    sa.Column('id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("(status = 'lapsed') = (lapsed_on IS NOT NULL)", name=op.f('ck_policies_lapsed_on_matches_status')),
    sa.CheckConstraint('annual_premium > 0', name=op.f('ck_policies_annual_premium_positive')),
    sa.CheckConstraint('deductible >= 0', name=op.f('ck_policies_deductible_non_negative')),
    sa.CheckConstraint('end_date > start_date', name=op.f('ck_policies_end_after_start')),
    sa.CheckConstraint('sum_insured > 0', name=op.f('ck_policies_sum_insured_positive')),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], name=op.f('fk_policies_customer_id_customers'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_policies')),
    sa.UniqueConstraint('policy_number', name=op.f('uq_policies_policy_number'))
    )
    op.create_index(op.f('ix_policies_customer_id'), 'policies', ['customer_id'], unique=False)
    op.create_table('claims',
    sa.Column('claim_number', sa.String(length=24), nullable=False),
    sa.Column('policy_id', sa.Uuid(), nullable=False),
    sa.Column('incident_type', sa.Enum('collision', 'theft', 'vandalism', 'natural_calamity', 'hospitalisation', 'surgery', 'day_care', 'fire', 'burglary', 'water_damage', name='incident_type', native_enum=False, create_constraint=True, length=32), nullable=False),
    sa.Column('incident_date', sa.Date(), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('claimed_amount', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('status', sa.Enum('submitted', 'processing', 'awaiting_review', 'escalated', 'approved', 'rejected', 'failed', name='status', native_enum=False, create_constraint=True, length=32), nullable=False),
    sa.Column('document_filename', sa.String(length=255), nullable=True),
    sa.Column('extracted_fields', postgresql.JSONB(astext_type=sa.Text()), nullable=True, comment='Intake agent output'),
    sa.Column('recommended_outcome', sa.Enum('approve', 'reject', 'escalate', name='recommended_outcome', native_enum=False, create_constraint=True, length=32), nullable=True),
    sa.Column('confidence', sa.Numeric(precision=4, scale=3), nullable=True),
    sa.Column('risk_score', sa.SmallInteger(), nullable=True),
    sa.Column('decision_rationale', sa.Text(), nullable=True),
    sa.Column('final_outcome', sa.Enum('approve', 'reject', name='final_outcome', native_enum=False, create_constraint=True, length=32), nullable=True),
    sa.Column('decided_by', sa.String(length=120), nullable=True),
    sa.Column('decided_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('override_reason', sa.Text(), nullable=True),
    sa.Column('id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('claimed_amount > 0', name=op.f('ck_claims_claimed_amount_positive')),
    sa.CheckConstraint('confidence IS NULL OR (confidence >= 0 AND confidence <= 1)', name=op.f('ck_claims_confidence_range')),
    sa.CheckConstraint('final_outcome IS NULL OR (decided_by IS NOT NULL AND decided_at IS NOT NULL)', name=op.f('ck_claims_final_outcome_has_reviewer')),
    sa.CheckConstraint('risk_score IS NULL OR (risk_score >= 0 AND risk_score <= 100)', name=op.f('ck_claims_risk_score_range')),
    sa.ForeignKeyConstraint(['policy_id'], ['policies.id'], name=op.f('fk_claims_policy_id_policies'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_claims')),
    sa.UniqueConstraint('claim_number', name=op.f('uq_claims_claim_number'))
    )
    op.create_index('ix_claims_created_at', 'claims', [sa.literal_column('created_at DESC')], unique=False)
    op.create_index('ix_claims_policy_id_incident_date', 'claims', ['policy_id', 'incident_date'], unique=False)
    op.create_index(op.f('ix_claims_status'), 'claims', ['status'], unique=False)
    op.create_table('premium_payments',
    sa.Column('policy_id', sa.Uuid(), nullable=False),
    sa.Column('installment_number', sa.SmallInteger(), nullable=False),
    sa.Column('due_date', sa.Date(), nullable=False),
    sa.Column('paid_date', sa.Date(), nullable=True),
    sa.Column('amount', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('status', sa.Enum('paid', 'late', 'missed', name='status', native_enum=False, create_constraint=True, length=32), nullable=False),
    sa.Column('id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("(status = 'missed') = (paid_date IS NULL)", name=op.f('ck_premium_payments_paid_date_matches_status')),
    sa.CheckConstraint('amount > 0', name=op.f('ck_premium_payments_amount_positive')),
    sa.CheckConstraint('installment_number >= 1', name=op.f('ck_premium_payments_installment_number_positive')),
    sa.ForeignKeyConstraint(['policy_id'], ['policies.id'], name=op.f('fk_premium_payments_policy_id_policies'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_premium_payments')),
    sa.UniqueConstraint('policy_id', 'installment_number', name='uq_premium_payments_policy_installment')
    )
    op.create_index(op.f('ix_premium_payments_policy_id'), 'premium_payments', ['policy_id'], unique=False)
    op.create_table('audit_log',
    sa.Column('id', sa.BigInteger(), sa.Identity(always=True), nullable=False),
    sa.Column('claim_id', sa.Uuid(), nullable=True),
    sa.Column('actor', sa.String(length=120), nullable=False, comment="e.g. 'system', 'customer_portal', 'reviewer:priya.nair'"),
    sa.Column('action', sa.String(length=64), nullable=False, comment="Dotted verb, e.g. 'claim.decided'"),
    sa.Column('before', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('after', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['claim_id'], ['claims.id'], name=op.f('fk_audit_log_claim_id_claims'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_audit_log'))
    )
    op.create_index(op.f('ix_audit_log_claim_id'), 'audit_log', ['claim_id'], unique=False)
    op.create_table('claim_runs',
    sa.Column('claim_id', sa.Uuid(), nullable=False),
    sa.Column('agent_name', sa.String(length=50), nullable=False),
    sa.Column('input', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('output', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('latency_ms', sa.Integer(), nullable=False),
    sa.Column('id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('latency_ms >= 0', name=op.f('ck_claim_runs_latency_ms_non_negative')),
    sa.ForeignKeyConstraint(['claim_id'], ['claims.id'], name=op.f('fk_claim_runs_claim_id_claims'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_claim_runs'))
    )
    op.create_index('ix_claim_runs_claim_id_created_at', 'claim_runs', ['claim_id', 'created_at'], unique=False)
    # ### end Alembic commands ###

    # Append-only audit trail, enforced by the database rather than application code: a bug, a rogue script
    # or a compromised app user cannot quietly rewrite who approved what. Corrections are new rows.
    # (TRUNCATE is a separate privilege, revoked from the app roles in Phase 5/11; the dev seed uses it.)
    op.execute(
        """
        CREATE FUNCTION audit_log_reject_mutation() RETURNS trigger LANGUAGE plpgsql AS $$
        BEGIN
            RAISE EXCEPTION 'audit_log is append-only: % is not allowed', TG_OP
                USING ERRCODE = 'insufficient_privilege';
        END;
        $$;
        """
    )
    op.execute(
        """
        CREATE TRIGGER audit_log_append_only
        BEFORE UPDATE OR DELETE ON audit_log
        FOR EACH ROW EXECUTE FUNCTION audit_log_reject_mutation();
        """
    )


def downgrade() -> None:
    op.execute("DROP TRIGGER IF EXISTS audit_log_append_only ON audit_log")
    op.execute("DROP FUNCTION IF EXISTS audit_log_reject_mutation()")
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_claim_runs_claim_id_created_at', table_name='claim_runs')
    op.drop_table('claim_runs')
    op.drop_index(op.f('ix_audit_log_claim_id'), table_name='audit_log')
    op.drop_table('audit_log')
    op.drop_index(op.f('ix_premium_payments_policy_id'), table_name='premium_payments')
    op.drop_table('premium_payments')
    op.drop_index(op.f('ix_claims_status'), table_name='claims')
    op.drop_index('ix_claims_policy_id_incident_date', table_name='claims')
    op.drop_index('ix_claims_created_at', table_name='claims')
    op.drop_table('claims')
    op.drop_index(op.f('ix_policies_customer_id'), table_name='policies')
    op.drop_table('policies')
    op.drop_table('customers')
    # ### end Alembic commands ###
